print('==== DESAFIO 02 DA AULA 04 ===')
dia = int(input('que dia você nasceu?\n'))
mes = input('que mês você nasceu?\n')
ano = int(input('que ano você nasceu?\n'))
print(f'você nasceu em {dia} de {mes} de {ano}.')
print('você nasceu em %d de %s de %d.' % (dia, mes, ano))
